# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170503_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detail',
            options={'ordering': ['date'], 'permissions': (('Can_account', 'Can into account.html'),)},
        ),
    ]
