# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20170503_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='cost',
            field=models.FloatField(default=0),
        ),
    ]
